[package]
name = "socks5rs"
version = "0.1.0"
authors = ["junyiz <junyime@qq.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "local"
path = "bin/local.rs"

[dependencies]
