[package]
name = "socksserver"
version = "0.1.0"
authors = ["junyiz <junyime@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"